use alloy_primitives::{Address, B256, Bytes as AlloyBytes, U256};
use alloy_rpc_types_engine::PayloadAttributes as EthPayloadAttributes;
use alloy_rpc_types_eth::Withdrawal;
use reth_engine_local::LocalPayloadAttributesBuilder;
use reth_node_api::{PayloadAttributes, PayloadAttributesBuilder};
use reth_primitives_traits::constants::MAXIMUM_GAS_LIMIT_BLOCK;
use serde::{Deserialize, Serialize};
use serde_with::{base64::Base64, serde_as};

use kasplex_reth_chainspec::spec::KasplexChainSpec;

/// Kasplex payload attributes for RPC.
#[derive(Clone, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
pub struct KasplexPayloadAttributes {
    /// The ETH payload attributes
    #[cfg_attr(feature = "serde", serde(flatten))]
    pub payload_attributes: EthPayloadAttributes,
    /// Base fee per gas for the Kasplex block.
    pub base_fee_per_gas: U256,
    /// The metadata for the Kasplex block.
    pub block_metadata: KasplexBlockMetadata,
}

impl PayloadAttributes for KasplexPayloadAttributes {
    /// Returns the timestamp to be used in the payload job.
    fn timestamp(&self) -> u64 {
        self.payload_attributes.timestamp()
    }

    /// Returns the withdrawals for the given payload attributes.
    fn withdrawals(&self) -> Option<&Vec<Withdrawal>> {
        self.payload_attributes.withdrawals()
    }

    /// Return the parent beacon block root for the payload attributes.
    fn parent_beacon_block_root(&self) -> Option<B256> {
        self.payload_attributes.parent_beacon_block_root()
    }
}

/// The metadata for a Kasplex block, which is generated by the Kasplex protocol.
#[serde_as]
#[derive(Clone, Debug, Default, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
pub struct KasplexBlockMetadata {
    /// The suggested fee recipient address for the block.
    pub beneficiary: Address,
    /// The gas limit for the block.
    pub gas_limit: u64,
    /// The timestamp for the block.
    pub timestamp: U256,
    /// The mix hash for the block.
    pub mix_hash: B256,
    /// The RLP-encoded transaction list for the block.
    pub tx_list: AlloyBytes,
    /// The extra data for the block.
    #[serde_as(as = "Base64")]
    pub extra_data: AlloyBytes,
}

/// Implement `PayloadAttributesBuilder` for `LocalPayloadAttributesBuilder<KasplexChainSpec>`,
/// to build `KasplexPayloadAttributes` from the local payload attributes builder.
impl PayloadAttributesBuilder<KasplexPayloadAttributes>
    for LocalPayloadAttributesBuilder<KasplexChainSpec>
{
    /// Return a new payload attribute from the builder.
    fn build(&self, timestamp: u64) -> KasplexPayloadAttributes {
        // Delegate to the underlying ETH payload builder to avoid self-recursion.
        let eth_payload_attributes =
            <Self as PayloadAttributesBuilder<EthPayloadAttributes>>::build(self, timestamp);

        KasplexPayloadAttributes {
            payload_attributes: eth_payload_attributes,
            base_fee_per_gas: U256::ZERO,
            block_metadata: KasplexBlockMetadata {
                beneficiary: Address::ZERO,
                timestamp: U256::from(timestamp),
                gas_limit: MAXIMUM_GAS_LIMIT_BLOCK,
                mix_hash: B256::ZERO,
                tx_list: AlloyBytes::new(),
                extra_data: AlloyBytes::new(),
            },
        }
    }
}

